name: lichess_client_dio
description: >-
  Lichess HTTP client based on Dio.
  Cross-platform API wrapper written in pure Dart.
version: 0.0.5
repository: https://github.com/alexrintt/lichess.dart
homepage: https://github.com/alexrintt/lichess.dart/tree/master/packages/lichess_client_dio
documentation: https://github.com/alexrintt/lichess.dart/tree/master/packages/lichess_client_dio
issue_tracker: https://github.com/alexrintt/lichess.dart/issues
funding:
  - https://donate.alexrintt.io
  - https://github.com/sponsors/alexrintt
  - https://www.patreon.com/RiccardoCescon

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  dio: ^5.0.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  lichess_client: ^0.0.14
  retrofit: ^4.0.1

dev_dependencies:
  build_runner: any
  build_test: any
  dependency_validator:
  dotenv: ^4.1.0
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  lints: ^2.0.1
  mockito: ^5.0.0
  nock: ^1.0.0
  retrofit_generator: ^5.0.0
  test: ^1.21.0
