name: shiro
description: "Lichess client for Dart."
version: 0.1.0
repository: https://github.com/alexrintt/shiro

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  http: ^0.13.5
  json_annotation: ^4.8.0
  path: ^1.8.0

dev_dependencies:
  build_runner: any
  build_test: any
  build_web_compilers: any
  collection: ^1.15.0
  dependency_validator:
  json_serializable: ^6.6.1
  lints: ^2.0.0
  mockito: ^5.0.0
  nock: ^1.0.0
  test: ^1.21.0
