name: shirou
description: "Lichess client for Dart."
version: 0.1.0
repository: https://github.com/alexrintt/shirou

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  dio: ^5.0.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  retrofit: 4.0.1

dev_dependencies:
  build_runner: any
  build_test: any
  build_web_compilers: any
  dependency_validator:
  dotenv: ^4.1.0
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  lint: ^2.0.1
  mockito: ^5.0.0
  nock: ^1.0.0
  retrofit_generator: ^5.0.0
  test: ^1.21.0
