name: lichess_client
description: "Lichess client for Dart."
version: 0.0.1
repository: https://github.com/alexrintt/lichess.dart

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

dev_dependencies:
  build_runner: any
  build_test: any
  dependency_validator:
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  lint: ^2.0.1
  mockito: ^5.0.0
  nock: ^1.0.0
  test: ^1.21.0
